# Generated by Django 3.2 on 2021-04-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='sizes_ferrules',
            field=models.IntegerField(choices=[('1', '1'), ('1.5', '1.5'), ('2', '2')]),
        ),
    ]
