# Generated by Django 3.2 on 2021-04-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210424_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('received_new_stock_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('new_stock_received_by', models.IntegerField(blank=True, default='0', null=True)),
                ('received_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('total_stock_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('date_issued', models.DateTimeField(null=True)),
                ('date_returned', models.DateTimeField(null=True)),
                ('stock_received_date', models.DateTimeField(null=True)),
                ('sizes_ferrules', models.CharField(blank=True, choices=[('N/A', 'n/a'), ('one', 1), ('one comma five', 1.5), ('two', 2), ('four', 4), ('six', 6), ('eight', 8), ('twenty five', 25), ('thirty five', 35), ('fifty', 50), ('seventy', 70), ('ninety five', 95), ('one hundred and twenty', 120), ('one hundred and fifty', 150), ('one hundred ans eighty five', 185), ('three hundred', 300)], max_length=100, null=True)),
                ('sizes_lugs', models.CharField(blank=True, choices=[('N/A', 'n/a'), ('three', 3), ('five', 5), ('thirty five by sixteen', '35 x 16'), ('thirty five by ten', '35 x 10'), ('thirty five by twelve', '35 x 12'), ('seventy by ten', '70 x 10'), ('seventy by twelve', '70 x 12'), ('seventy by sixteen', '70 x 16'), ('ninety five by ten', '95 x 10'), ('ninety five by twelve', '95 x 12'), ('ninety five by sixteen', '95 x 16'), ('one hundred and twenty by ten', '120 x 10'), ('one hundred and twenty by twelve', '120 x 12'), ('one hundred and twenty by sixteen', '120 x 16'), ('one hundred and fifty by ten', '150 x 10'), ('one hundred and fifty by twelve', '150 x 12'), ('one hundred and fifty by sixteen', '150 x 16'), ('one hundred and eighty five by ten', '185 x 10'), ('one hundred and eighty five by twelve', '185 x 12'), ('one hundred and eighty five by sixteen', '185 x 16'), ('two hundred and forty by ten ', '240 x 10'), ('two hundred and forty by twelve ', '240 x 12'), ('two hundred and forty by sixteen ', '240 x 16'), ('three hundred by ten', '300 x 10'), ('three hundred by twelve', '300 x 12'), ('three hundred by sixteen', '300 x 16')], max_length=100, null=True)),
                ('sizes_others', models.CharField(blank=True, choices=[('NOT_APPLICABLE', 'n/a'), ('SMALL', 'small'), ('MEDIUM', 'medium'), ('LARGE', 'large '), ('EXTRA_LARGE', 'extra-large')], max_length=100, null=True)),
                ('returned', models.BooleanField(blank=True, default=False, null=True)),
                ('condition_returned', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
