# Generated by Django 3.2 on 2021-04-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_stocks_sizes_ferrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='sizes_ferrules',
            field=models.IntegerField(choices=[('one', 1), ('one point five', 1.5)]),
        ),
    ]
