# Generated by Django 3.2 on 2021-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_stocks_sizes_ferrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='sizes_ferrules',
            field=models.IntegerField(choices=[('one', '1'), ('one point five', '1.5'), ('two', '2')]),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='sizes_words',
            field=models.CharField(choices=[('N/A', 'n/a'), ('SMALL', 'small'), ('MEDIUM', 'medium'), ('LARGE', 'large '), ('EXTRA_LARGE', 'extra-large')], max_length=100),
        ),
    ]
