# Generated by Django 3.2 on 2021-04-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='new_stock_received_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
