# Generated by Django 3.2 on 2021-04-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210428_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='start_date',
        ),
    ]
