# Generated by Django 3.2 on 2021-04-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_stocks_sizes_ferrules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='received_to_stock',
            new_name='received_stock',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='stock_quantity',
            new_name='total_stock_quantity',
        ),
        migrations.AlterField(
            model_name='stocks',
            name='sizes_ferrules',
            field=models.CharField(choices=[('N/A', 'n/a'), ('zero', 'zero'), ('one', 1), ('one comma five', 1.5), (2, 2), (4, 'four'), (6, 'six'), (8, 'eight'), (25, 'twenty five'), (35, 'thirty five'), (50, 'fifty'), (70, 'seventy'), (95, 'ninety five'), (120, 'one hundred and twenty'), (150, 'one hundred and fifty'), (185, 'one hundred ans eighty five'), (300, 'three hundred')], max_length=100),
        ),
    ]
