# Generated by Django 3.2 on 2021-04-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210420_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
