# Generated by Django 3.2 on 2021-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210421_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('FERRULES', 'ferrules'), ('LUGS', 'lugs'), ('INSULATION TAPE', 'insulation-tape')], max_length=100, null=True),
        ),
    ]
